import Head from 'next/head'
import Navbar from '../components/navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sol Youns Portfolio</title>
        <meta name="description" content="Generated by Sol Youn" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
      <h1>My Portfolio</h1>
      

    </div>
  )
}
